# What music player to use
# Currently only supports mpv
player = "mpv"

# The name of your music directory
# If this is a relative path, it's
# relative to your home directory.
music_dir = "music"

# The file to create and manage in
# your music directory
storage_file = ".markov_music_data"

# Default seconds to seek by
seek_seconds = 0.2

# How much to increase/decrease the volume by
volume_step = 1
