[package]
name = "markov-music"
version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]

[dependencies]
clap = "2"
mpv = "0.2"
rand = "0.3"
same-file = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
termion = "1.5"
walkdir = "1"
