[package]
name = "markov-music"
version = "0.0.2"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]

[dependencies]
clap = "2"
lazy_static = "0.2"
mpv = "0.2"
ncurses = "5"
pancurses = "0.9"
rand = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.4"
